/* eslint-disable import/no-mutable-exports */
/* eslint-disable camelcase */
import Scale from "../Scale";
import { AEOLIAN_b1, AUGMENTED_TRIAD, BEBOP_DOMINANT, BEBOP_DORIAN, BEBOP_HARMONIC_MINOR, BEBOP_MAJOR, BEBOP_MELODIC_MINOR, BLUES_a4, BLUES_b5, BLUES_MINOR, CHROMATIC, DIMINISHED_7th, DOM7b5, DORIAN, DORIAN_a4, DORIAN_b2, DORIAN_b5, DOUBLE_HARMONIC, EGYPCIAN, HALF_DIMINISHED, HARMONIC_MAJOR, HARMONIC_MINOR, HUNGARIAN_MINOR, IONIAN_a5, IONIAN_AUGMENTED_a2, LOCRIAN, LOCRIAN_a2, LOCRIAN_a6, LOCRIAN_bb3_bb7, LOCRIAN_bb7, LYDIAN, LYDIAN_a2, LYDIAN_a2_a6, LYDIAN_a5, LYDIAN_b3, LYDIAN_b7, MAJOR, MELODIC_MINOR, MESSIAEN_III_INV, MESSIAEN_II_TRUNCATED_n3, MESSIAEN_INV_III_V_TRUNCATED_n2, MESSIAEN_IV, MESSIAEN_V, MESSIAEN_VI, MESSIAEN_VII, MESSIAEN_V_TRUNCATED, MINOR, MIXOLYDIAN, MIXOLYDIAN_b13, MIXOLYDIAN_b2, MIXOLYDIAN_b9_b13, NEAPOLITAN_MAJOR, NEAPOLITAN_MINOR, ORIENTAL, PENTATONIC, PENTATONIC_MINOR, PHRYGIAN, PHRYGIAN_b4, RAGA_INDRUPRIYA_INDIA, SUPERLOCRIAN, SUPERLOCRIAN_bb7, ULTRAPHRYGIAN, WHOLE_TONE } from "./constants";

export function initializeSets() {
  DIATONIC_SCALES = new Set([
    MAJOR,
    DORIAN,
    PHRYGIAN,
    LYDIAN,
    MIXOLYDIAN,
    MINOR,
    LOCRIAN,
  ]);

  HEPTATONIC_SCALES = new Set<Scale>([...DIATONIC_SCALES,
    ...[
      HARMONIC_MINOR,
      LOCRIAN_a6,
      IONIAN_a5,
      DORIAN_a4,
      MIXOLYDIAN_b9_b13,
      LYDIAN_a2,
      SUPERLOCRIAN_bb7,

      HARMONIC_MAJOR,
      DORIAN_b5,
      PHRYGIAN_b4,
      LYDIAN_b3,
      MIXOLYDIAN_b2,
      AEOLIAN_b1,
      LOCRIAN_bb7,

      MELODIC_MINOR,
      DORIAN_b2,
      LYDIAN_a5,
      LYDIAN_b7,
      MIXOLYDIAN_b13,
      LOCRIAN_a2,
      SUPERLOCRIAN,

      DOUBLE_HARMONIC,
      LYDIAN_a2_a6,
      ULTRAPHRYGIAN,
      HUNGARIAN_MINOR,
      ORIENTAL,
      IONIAN_AUGMENTED_a2,
      LOCRIAN_bb3_bb7,

      NEAPOLITAN_MINOR,
      NEAPOLITAN_MAJOR,
    ],
  ]);

  BEBOP_SCALES = new Set([
    BEBOP_MAJOR,
    BEBOP_DORIAN,
    BEBOP_DOMINANT,
    BEBOP_MELODIC_MINOR,
    BEBOP_HARMONIC_MINOR,
  ]);

  PENTATONIC_SCALES = new Set([
    PENTATONIC_MINOR,
    PENTATONIC,
    EGYPCIAN,
    BLUES_MINOR,
  ]);

  HEXATONIC_SCALES = new Set([
    BLUES_b5,
    BLUES_a4,
    WHOLE_TONE,
  ]);

  SYMMETRIC_SCALES = new Set([
    CHROMATIC,
    WHOLE_TONE,
    AUGMENTED_TRIAD,
    DIMINISHED_7th,
    MESSIAEN_V_TRUNCATED,
    DOM7b5,
    MESSIAEN_INV_III_V_TRUNCATED_n2,
    HALF_DIMINISHED,
    MESSIAEN_V,
    RAGA_INDRUPRIYA_INDIA,
    MESSIAEN_II_TRUNCATED_n3,
    MESSIAEN_III_INV,
    MESSIAEN_IV,
    MESSIAEN_VI,
    MESSIAEN_VII,
  ]);

  COMMON = new Set<Scale>([
    ...HEPTATONIC_SCALES,
    ...PENTATONIC_SCALES,
    ...HEXATONIC_SCALES,
    ...BEBOP_SCALES,
    ...SYMMETRIC_SCALES,
  ]);
}

export let DIATONIC_SCALES: Set<Scale>;

export let HEPTATONIC_SCALES: Set<Scale>;

export let BEBOP_SCALES: Set<Scale>;

export let PENTATONIC_SCALES: Set<Scale>;

export let HEXATONIC_SCALES: Set<Scale>;

export let COMMON: Set<Scale>;

export let SYMMETRIC_SCALES: Set<Scale>;
