import { IntervalDiatonic } from './IntervalDiatonic';
import { IntervalDiatonicAlt } from './IntervalDiatonicAlt';
import { Quality } from './Quality';
import { qualities, intervalDiatonics } from '../initializer';

export default () => {
    if (IntervalDiatonicAlt.PERFECT_UNISON)
        return;

    qualities.default();
    intervalDiatonics.default();

    IntervalDiatonicAlt.PERFECT_UNISON = IntervalDiatonicAlt.from(IntervalDiatonic.UNISON, Quality.PERFECT);
    IntervalDiatonicAlt.DIMINISHED_SECOND = IntervalDiatonicAlt.from(IntervalDiatonic.SECOND, Quality.DIMINISHED);
    IntervalDiatonicAlt.MINOR_SECOND = IntervalDiatonicAlt.from(IntervalDiatonic.SECOND, Quality.MINOR);
    IntervalDiatonicAlt.AUGMENTED_UNISON = IntervalDiatonicAlt.from(IntervalDiatonic.UNISON, Quality.AUGMENTED);
    IntervalDiatonicAlt.DOUBLY_AUGMENTED_UNISON = IntervalDiatonicAlt.from(IntervalDiatonic.UNISON, Quality.DOUBLY_AUGMENTED);
    IntervalDiatonicAlt.MAJOR_SECOND = IntervalDiatonicAlt.from(IntervalDiatonic.SECOND, Quality.MAJOR);
    IntervalDiatonicAlt.DIMINISHED_THIRD = IntervalDiatonicAlt.from(IntervalDiatonic.THIRD, Quality.DIMINISHED);
    IntervalDiatonicAlt.DOUBLY_DIMINISHED_THIRD = IntervalDiatonicAlt.from(IntervalDiatonic.THIRD, Quality.DOUBLY_DIMINISHED);
    IntervalDiatonicAlt.MINOR_THIRD = IntervalDiatonicAlt.from(IntervalDiatonic.THIRD, Quality.MINOR);
    IntervalDiatonicAlt.AUGMENTED_SECOND = IntervalDiatonicAlt.from(IntervalDiatonic.SECOND, Quality.AUGMENTED);
    IntervalDiatonicAlt.DOUBLY_AUGMENTED_SECOND = IntervalDiatonicAlt.from(IntervalDiatonic.SECOND, Quality.DOUBLY_AUGMENTED);
    IntervalDiatonicAlt.MAJOR_THIRD = IntervalDiatonicAlt.from(IntervalDiatonic.THIRD, Quality.MAJOR);
    IntervalDiatonicAlt.DIMINISHED_FOURTH = IntervalDiatonicAlt.from(IntervalDiatonic.FOURTH, Quality.DIMINISHED);
    IntervalDiatonicAlt.DOUBLY_DIMINISHED_FOURTH = IntervalDiatonicAlt.from(IntervalDiatonic.FOURTH, Quality.DOUBLY_DIMINISHED);
    IntervalDiatonicAlt.PERFECT_FOURTH = IntervalDiatonicAlt.from(IntervalDiatonic.FOURTH, Quality.PERFECT);
    IntervalDiatonicAlt.AUGMENTED_THIRD = IntervalDiatonicAlt.from(IntervalDiatonic.THIRD, Quality.AUGMENTED);
    IntervalDiatonicAlt.DOUBLY_AUGMENTED_THIRD = IntervalDiatonicAlt.from(IntervalDiatonic.THIRD, Quality.DOUBLY_AUGMENTED);
    IntervalDiatonicAlt.DIMINISHED_FIFTH = IntervalDiatonicAlt.from(IntervalDiatonic.FIFTH, Quality.DIMINISHED);
    IntervalDiatonicAlt.DOUBLY_DIMINISHED_FIFTH = IntervalDiatonicAlt.from(IntervalDiatonic.FIFTH, Quality.DOUBLY_DIMINISHED);
    IntervalDiatonicAlt.AUGMENTED_FOURTH = IntervalDiatonicAlt.from(IntervalDiatonic.FOURTH, Quality.AUGMENTED);
    IntervalDiatonicAlt.DOUBLY_AUGMENTED_FOURTH = IntervalDiatonicAlt.from(IntervalDiatonic.FOURTH, Quality.DOUBLY_AUGMENTED);
    IntervalDiatonicAlt.PERFECT_FIFTH = IntervalDiatonicAlt.from(IntervalDiatonic.FIFTH, Quality.PERFECT);
    IntervalDiatonicAlt.DIMINISHED_SIXTH = IntervalDiatonicAlt.from(IntervalDiatonic.SIXTH, Quality.DIMINISHED);
    IntervalDiatonicAlt.DOUBLY_DIMINISHED_SIXTH = IntervalDiatonicAlt.from(IntervalDiatonic.SIXTH, Quality.DOUBLY_DIMINISHED);
    IntervalDiatonicAlt.MINOR_SIXTH = IntervalDiatonicAlt.from(IntervalDiatonic.SIXTH, Quality.MINOR);
    IntervalDiatonicAlt.AUGMENTED_FIFTH = IntervalDiatonicAlt.from(IntervalDiatonic.FIFTH, Quality.AUGMENTED);
    IntervalDiatonicAlt.DOUBLY_AUGMENTED_FIFTH = IntervalDiatonicAlt.from(IntervalDiatonic.FIFTH, Quality.DOUBLY_AUGMENTED);
    IntervalDiatonicAlt.MAJOR_SIXTH = IntervalDiatonicAlt.from(IntervalDiatonic.SIXTH, Quality.MAJOR);
    IntervalDiatonicAlt.DIMINISHED_SEVENTH = IntervalDiatonicAlt.from(IntervalDiatonic.SEVENTH, Quality.DIMINISHED);
    IntervalDiatonicAlt.DOUBLY_DIMINISHED_SEVENTH = IntervalDiatonicAlt.from(IntervalDiatonic.SEVENTH, Quality.DOUBLY_DIMINISHED);
    IntervalDiatonicAlt.MINOR_SEVENTH = IntervalDiatonicAlt.from(IntervalDiatonic.SEVENTH, Quality.MINOR);
    IntervalDiatonicAlt.AUGMENTED_SIXTH = IntervalDiatonicAlt.from(IntervalDiatonic.SIXTH, Quality.AUGMENTED);
    IntervalDiatonicAlt.DOUBLY_AUGMENTED_SIXTH = IntervalDiatonicAlt.from(IntervalDiatonic.SIXTH, Quality.DOUBLY_AUGMENTED);
    IntervalDiatonicAlt.MAJOR_SEVENTH = IntervalDiatonicAlt.from(IntervalDiatonic.SEVENTH, Quality.MAJOR);
    IntervalDiatonicAlt.DIMINISHED_OCTAVE = IntervalDiatonicAlt.from(IntervalDiatonic.OCTAVE, Quality.DIMINISHED);
    IntervalDiatonicAlt.DOUBLY_DIMINISHED_OCTAVE = IntervalDiatonicAlt.from(IntervalDiatonic.OCTAVE, Quality.DOUBLY_DIMINISHED);
    IntervalDiatonicAlt.PERFECT_OCTAVE = IntervalDiatonicAlt.from(IntervalDiatonic.OCTAVE, Quality.PERFECT);
    IntervalDiatonicAlt.AUGMENTED_SEVENTH = IntervalDiatonicAlt.from(IntervalDiatonic.SEVENTH, Quality.AUGMENTED);
    IntervalDiatonicAlt.DOUBLY_AUGMENTED_SEVENTH = IntervalDiatonicAlt.from(IntervalDiatonic.SEVENTH, Quality.DOUBLY_AUGMENTED);
    IntervalDiatonicAlt.DIMINISHED_NINTH = IntervalDiatonicAlt.from(IntervalDiatonic.NINTH, Quality.DIMINISHED);
    IntervalDiatonicAlt.DOUBLY_DIMINISHED_NINTH = IntervalDiatonicAlt.from(IntervalDiatonic.NINTH, Quality.DOUBLY_DIMINISHED);
    IntervalDiatonicAlt.MINOR_NINTH = IntervalDiatonicAlt.from(IntervalDiatonic.NINTH, Quality.MINOR);
    IntervalDiatonicAlt.AUGMENTED_OCTAVE = IntervalDiatonicAlt.from(IntervalDiatonic.OCTAVE, Quality.AUGMENTED);
    IntervalDiatonicAlt.MAJOR_NINTH = IntervalDiatonicAlt.from(IntervalDiatonic.NINTH, Quality.MAJOR);
    IntervalDiatonicAlt.DIMINISHED_TENTH = IntervalDiatonicAlt.from(IntervalDiatonic.TENTH, Quality.DIMINISHED);
    IntervalDiatonicAlt.DOUBLY_DIMINISHED_TENTH = IntervalDiatonicAlt.from(IntervalDiatonic.TENTH, Quality.DOUBLY_DIMINISHED);
    IntervalDiatonicAlt.MINOR_TENTH = IntervalDiatonicAlt.from(IntervalDiatonic.TENTH, Quality.MINOR);
    IntervalDiatonicAlt.AUGMENTED_NINTH = IntervalDiatonicAlt.from(IntervalDiatonic.NINTH, Quality.AUGMENTED);
    IntervalDiatonicAlt.DOUBLY_AUGMENTED_NINTH = IntervalDiatonicAlt.from(IntervalDiatonic.NINTH, Quality.DOUBLY_AUGMENTED);
    IntervalDiatonicAlt.MAJOR_TENTH = IntervalDiatonicAlt.from(IntervalDiatonic.TENTH, Quality.MAJOR);
    IntervalDiatonicAlt.DIMINISHED_ELEVENTH = IntervalDiatonicAlt.from(IntervalDiatonic.ELEVENTH, Quality.DIMINISHED);
    IntervalDiatonicAlt.DOUBLY_DIMINISHED_ELEVENTH = IntervalDiatonicAlt.from(IntervalDiatonic.ELEVENTH, Quality.DOUBLY_DIMINISHED);
    IntervalDiatonicAlt.PERFECT_ELEVENTH = IntervalDiatonicAlt.from(IntervalDiatonic.ELEVENTH, Quality.MINOR);
    IntervalDiatonicAlt.AUGMENTED_TENTH = IntervalDiatonicAlt.from(IntervalDiatonic.TENTH, Quality.AUGMENTED);
    IntervalDiatonicAlt.DOUBLY_AUGMENTED_TENTH = IntervalDiatonicAlt.from(IntervalDiatonic.TENTH, Quality.DOUBLY_AUGMENTED);
    IntervalDiatonicAlt.DIMINISHED_TWELFTH = IntervalDiatonicAlt.from(IntervalDiatonic.TWELFTH, Quality.DIMINISHED);
    IntervalDiatonicAlt.DOUBLY_DIMINISHED_TWELFTH = IntervalDiatonicAlt.from(IntervalDiatonic.TWELFTH, Quality.DOUBLY_DIMINISHED);
    IntervalDiatonicAlt.AUGMENTED_ELEVENTH = IntervalDiatonicAlt.from(IntervalDiatonic.ELEVENTH, Quality.AUGMENTED);
    IntervalDiatonicAlt.DOUBLY_AUGMENTED_ELEVENTH = IntervalDiatonicAlt.from(IntervalDiatonic.ELEVENTH, Quality.DOUBLY_AUGMENTED);
    IntervalDiatonicAlt.PERFECT_TWELFTH = IntervalDiatonicAlt.from(IntervalDiatonic.TWELFTH, Quality.PERFECT);
    IntervalDiatonicAlt.DIMINISHED_THIRTEENTH = IntervalDiatonicAlt.from(IntervalDiatonic.THIRTEENTH, Quality.DIMINISHED);
    IntervalDiatonicAlt.DOUBLY_DIMINISHED_THIRTEENTH = IntervalDiatonicAlt.from(IntervalDiatonic.THIRTEENTH, Quality.DOUBLY_DIMINISHED);
    IntervalDiatonicAlt.MINOR_THIRTEENTH = IntervalDiatonicAlt.from(IntervalDiatonic.THIRTEENTH, Quality.MINOR);
    IntervalDiatonicAlt.AUGMENTED_TWELFTH = IntervalDiatonicAlt.from(IntervalDiatonic.TWELFTH, Quality.AUGMENTED);
    IntervalDiatonicAlt.DOUBLY_AUGMENTED_TWELFTH = IntervalDiatonicAlt.from(IntervalDiatonic.TWELFTH, Quality.DOUBLY_AUGMENTED);
    IntervalDiatonicAlt.MAJOR_THIRTEENTH = IntervalDiatonicAlt.from(IntervalDiatonic.THIRTEENTH, Quality.MAJOR);
    IntervalDiatonicAlt.DIMINISHED_FOURTEENTH = IntervalDiatonicAlt.from(IntervalDiatonic.FOURTEENTH, Quality.DIMINISHED);
    IntervalDiatonicAlt.DOUBLY_DIMINISHED_FOURTEENTH = IntervalDiatonicAlt.from(IntervalDiatonic.FOURTEENTH, Quality.DOUBLY_DIMINISHED);
    IntervalDiatonicAlt.MINOR_FOURTEENTH = IntervalDiatonicAlt.from(IntervalDiatonic.FOURTEENTH, Quality.MINOR);
    IntervalDiatonicAlt.AUGMENTED_THIRTEENTH = IntervalDiatonicAlt.from(IntervalDiatonic.THIRTEENTH, Quality.AUGMENTED);
    IntervalDiatonicAlt.DOUBLY_AUGMENTED_THIRTEENTH = IntervalDiatonicAlt.from(IntervalDiatonic.THIRTEENTH, Quality.DOUBLY_AUGMENTED);
    IntervalDiatonicAlt.MAJOR_FOURTEENTH = IntervalDiatonicAlt.from(IntervalDiatonic.FOURTEENTH, Quality.MAJOR);
    IntervalDiatonicAlt.DIMINISHED_FIFTEENTH = IntervalDiatonicAlt.from(IntervalDiatonic.FIFTEENTH, Quality.DIMINISHED);
    IntervalDiatonicAlt.DOUBLY_DIMINISHED_FIFTEENTH = IntervalDiatonicAlt.from(IntervalDiatonic.FIFTEENTH, Quality.DOUBLY_DIMINISHED);
    IntervalDiatonicAlt.PERFECT_FIFTEENTH = IntervalDiatonicAlt.from(IntervalDiatonic.FIFTEENTH, Quality.PERFECT);
    IntervalDiatonicAlt.AUGMENTED_FOURTEENTH = IntervalDiatonicAlt.from(IntervalDiatonic.FOURTEENTH, Quality.AUGMENTED);
    IntervalDiatonicAlt.DOUBLY_AUGMENTED_FOURTEENTH = IntervalDiatonicAlt.from(IntervalDiatonic.FOURTEENTH, Quality.DOUBLY_AUGMENTED);
    IntervalDiatonicAlt.AUGMENTED_FIFTEENTH = IntervalDiatonicAlt.from(IntervalDiatonic.FIFTEENTH, Quality.AUGMENTED);
    IntervalDiatonicAlt.DOUBLY_AUGMENTED_FIFTEENTH = IntervalDiatonicAlt.from(IntervalDiatonic.FIFTEENTH, Quality.DOUBLY_AUGMENTED);
}